version: '3.7'

services:
  archbot:
    #build: .
    image: ghcr.io/sksat/archbot-rs:main
    restart: always

    volumes:
      - type: bind
        source: ./config.toml
        target: /app/config.toml
